import { Button, VerticalBox, TextEdit, ScrollView, HorizontalBox, ComboBox, ListView, StandardButton, SpinBox } from "std-widgets.slint";
import { Theme } from "theme.slint";

export { Theme }

export component AppWindow inherits Window {
    background: Theme.background;

    title: "Bypassing Prohibitions";
    height: 400px;
    width: 600px;

    in-out property <bool> dark-mode <=> Theme.is-dark; // переменная для управления темой и построения моста к бэку
    
    // массив для combobox
    in-out property <[string]> combo_options: ["Auto"];

    // начальное значение для отображения логов
    in-out property <string> status_log: "Готов к работе...";
    in-out property <string> time_connect_to_site; // переменная получающая время подключения
    
    property <string> selected_config: root.combo_options[0]; // получение начального значения для combobox
    property <bool> show_settings: false; // флаг для управления окном настроек
    property <string> url_to_activate; // переменная получающая url
    
    // событие для подключения 
    callback activate_clicked(string, string); 
    
    callback config_add_clicked(string); // событие для добавления в конфиги
    callback exit_from_settings(string); // событие для выхода с получением настроек
    callback save_config(bool); // событие для отправки выбранной темы на бэк

    // главное окно
    main_layout := Rectangle {

        VerticalLayout {
            padding: 15px;
            spacing: 10px;

            HorizontalLayout {
                alignment: end;
                spacing: 10px;
                
                Button {
                    width: 40px;
                    height: 40px;
                    text: "⚙";
                    clicked => { root.show_settings = true; }
                }

                Rectangle { } 
            }

            TextEdit { 
                width: parent.width - 40px; 
                height: 60px;
                x: 20px;  
                placeholder-text: "Укажите ссылку (https://google.com)..."; 
                font-size: 14px; 
                edited(text) => { root.url_to_activate = text; } 
            } 

            ComboBox { 
                x: 20px;
                width: parent.width - 40px; 
                model: root.combo_options;
                selected(current-value) => { root.selected_config = current_value;  }
            }

            HorizontalBox {
                width: 100%;
                alignment: center;
                spacing: 15px;
            
                Button {
                    height: 40px; width: 120px;

                    text: "Активировать";
                    clicked => { root.activate_clicked(root.url_to_activate, root.selected_config); }
                }  

                Button {
                    text: "Добавить в конфигурацию";
                    clicked => { root.config_add_clicked(root.url_to_activate) }
                }
            }

            TextEdit {
                x: 15px;
                width: parent.width - 40px; 

                text: root.status_log;

                font-family: "Consolas";
                font-size: 14px;
                read-only: true;
                wrap: word-wrap;
                horizontal-alignment: left;
            }
        }
    }

    // окно настроек
    if (root.show_settings) : TouchArea {

        Rectangle {
            background: rgba(0, 0, 0, 0.4);
        }

        Rectangle {
            width: 80%;
            height: 85%;
            background: root.background;
            border-radius: 8px;
            border-width: 1px;
            border-color: #444;

            VerticalBox {
                padding: 20px;
                alignment: start;

                Text {
                    text: "Настройки приложения";
                    font-size: 18px;
                    horizontal-alignment: center;
                }

                Text {  }
                Text { text: "Укажите время подключения..."; }
                TextEdit { 
                    height: 50px;
                    text <=> root.time_connect_to_site;
                }

                Text {  }
                Text { text: "Темы:"; }
                ComboBox {
                    model: ["Темная", "Светлая"];
                    current-value: Theme.is-dark ? "Темная" : "Светлая";
            
                    selected(val) => {
                        Theme.is-dark = (val == "Темная");
                        root.save_config(Theme.is-dark);
                    }
                }

                Text {  }
                Rectangle {

                    Button {
                        text: "Просмотреть текущую конфигурацю";
                    }
                }

                Rectangle {

                    Button {
                        text: "Закрыть и сохранить";
                        
                        clicked => { 
                            root.show_settings = false; 
                            root.exit_from_settings(root.time_connect_to_site);
                        }
                    }
                }
            }
        }
    }
}
