import { Button, VerticalBox, TextEdit, ScrollView, HorizontalBox, ComboBox, ListView } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Bypassing Prohibitions";

    height: 400px;
    width: 600px;

    in-out property <string> status_log: "Готов к работе...";
    in-out property <[string]> combo_options: ["Auto"];

    property <string> url_to_activate;

    property <string> selected_config: root.combo_options[0]; 

    callback activate_clicked(string, string);
    callback config_add_clicked(string);


    Rectangle {

        TextEdit {
            height: 55px; width: parent.width - 40px;
            x: 19px; y: 23px; 

            placeholder-text: "Укажите ссылку (https://google.com)";
            font-size: 13.7px;
            edited(text) => { root.url_to_activate = text; }
        }

        ComboBox {
            y: 90px;
            width: parent.width - 40px;

            model: root.combo_options;
            current-index: 0;
            selected(current-value) => { root.selected_config = current_value;  }
        }

        HorizontalBox {
            y: 130px; x: 160px;
            spacing: 15px;
        
            Button {
                height: 40px; width: 120px;

                text: "Активировать";
                clicked => { root.activate_clicked(root.url_to_activate, root.selected_config); }
            }  

            Button {
                height: 40px; width: 179px;

                text: "Добавить в конфигурацию";
                clicked => { root.config_add_clicked(root.url_to_activate) }
            }
        }

        Rectangle {
            x: 19px; y: 200px;
            width: 567px; height: 180px;
            background: #2a2a2a;
            border-radius: 4px;
            clip: true;

            ScrollView {
                width: 100%;
                height: 100%;
                viewport-width: parent.width - 20px; 

                Text {
                    x: 15px; y: 10px;
                    width: parent.width; 

                    text: root.status_log;

                    color: #00ff00;
                    font-family: "Consolas";
                    font-size: 14px;
                    wrap: word-wrap;
                    horizontal-alignment: left;
                }
            }
        }
    }
}
