export global Theme {
    in-out property <bool> is-dark: true;
    out property <color> background: is-dark ? #1a1c20 : #568ac2;
    out property <color> background_secind_window: is-dark ? #1a1c20 : #568ac2;
    out property <color> item-bg: is-dark ? #2d3139 : #336090;
    out property <color> item-bg-alt: is-dark ? #252930 : #406d9d;
    out property <color> border: is-dark ? #3e4451 : #dadcde;
    out property <color> accent: #2563eb;
}
